# Generated by Django 5.1.6 on 2025-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image1', models.FilePathField()),
                ('image2', models.FilePathField()),
                ('image3', models.FilePathField()),
                ('image4', models.FilePathField()),
            ],
        ),
    ]
