# Generated by Django 5.1.6 on 2025-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.CharField(max_length=100),
        ),
    ]
